---
- hosts: sat63
  vars_files:
    - ../../vars/satellite_common.local.yml
    - ../../vars/satellite_63.yml
  roles:
    - partition-disk
    - redhat_subscriptions
    - satellite6_repositories
    - update_os_packages
    - install_satellite6
