---
- name: Install katello-ca-consumer-latest
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "7"
  yum:
    name: "{{ repository_url }}/pub/katello-ca-consumer-latest.noarch.rpm"
    state: present

- name: Register with activationkey and consume subscriptions from Dogfood Server.
  redhat_subscription:
    state: present
    activationkey: "{{ redhat_subscriptions_activation_key }}"
    org_id: "{{ redhat_subscriptions_organization }}"
